cargo-features = ["strip"]
[workspace]
members = [
  linux-Execute_Shellcode,
  windows-Basic_Enum,
  windows-Memory_Buffer,
]

[profile.release]
strip = "symbols"
panic = "abort"
trim-path = true
opt-level = "z"
lto = true
